// Code generated by MockGen. DO NOT EDIT.
// Source: email.go

// Package mock_notifier is a generated GoMock package.
package mock_notifier

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gomail_v2 "gopkg.in/gomail.v2"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// DialAndSend mocks base method.
func (m *MockEmailSender) DialAndSend(message ...*gomail_v2.Message) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range message {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DialAndSend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DialAndSend indicates an expected call of DialAndSend.
func (mr *MockEmailSenderMockRecorder) DialAndSend(message ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DialAndSend", reflect.TypeOf((*MockEmailSender)(nil).DialAndSend), message...)
}
